services:
  - type: web
    name: mediquery
    runtime: python
    buildCommand: "pip install -r requirements.txt && pip install -e ."
    startCommand: "gunicorn app:app --workers 2 --timeout 120"
    plan: free
    envVars:
      - key: PINECONE_API_KEY
        sync: false          # You fill this in Render dashboard
      - key: NVIDIA_NIM
        sync: false          # You fill this in Render dashboard
      - key: PYTHON_VERSION
        value: "3.11.0"
